config_docker: &config_docker
  docker:
    - image: jspc/ci-worker:1.3.0
  resource_class: small

version: 2.1
jobs:
  build:
    <<: *config_docker
    steps:
      - checkout
      - run: make terraform-ci
      - run: make bootstrap

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: BUILD
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
